# VERSION 1.3
all_nuts = (
        'calories', 'protein', 'carbs', 'fiber', 'fat', 'cholesterol', 'calcium', 'iron', 'magnesium', 'potassium',
        'sodium', 'zinc', 'vitamin a', 'thiamine', 'vitamin e', 'riboflavin', 'niacin', 'vitamin b6', 'folate',
        'vitamin c', 'vitamin b12', 'selenium', 'sugar', 'vitamin d')

daily_doses = {
    'calories': (3500, 'kilojoules', 4500),
    'protein': (140, 'grams', 0),
    'carbs': (280, 'grams', 0),
    'fiber': (38, 'grams', 0),
    'fat': (100, 'grams', 0),
    'cholesterol': (0, 'mg', 300),
    'calcium': (1000, 'mg', 2500),
    'iron': (8, 'mg', 0),
    'magnesium': (420, 'mg', 350),
    'sodium': (1300, 'mg', 2300),
    'zinc': (11, 'mg', 40),
    'vitamin a': (900, 'ug', 3000),
    'thiamine': (1.2, 'mg', 0),
    'vitamin e': (15, 'mg', 1000),
    'riboflavin': (1.2, 'mg', 0),
    'niacin': (16, 'mg', 35),
    'vitamin b6': (1.3, 'mg', 100),
    'folate': (400, 'ug', 1000),
    'vitamin c': (120, 'ug', 2000),
    'vitamin b12': (2.4, 'ug', 0),
    'selenium': (0, 'ug', 400),
    'sugar': (0, 'g', 50),
    'vitamin d': (600, 'IU', 4000),
    'potassium': (3400, 'mg', 6000)
}

foods = {
    'whole wheat (Arnold)': {
        'quantity': 1,
        'measure': 'slice',
        'weight': 43,
        'unit': 'g',
        'calories': 110,
        'protein': 4,
        'carbs': 21,
        'fiber': 3,
        'fat': 2,
        'cholesterol': 0,
        'calcium': 45,
        'iron': 0.9,
        'magnesium': 23,
        'potassium': 100,
        'sodium': 180,
        'zinc': .0,
        'vitamin a': 0,
        'thiamine': 0.0,
        'vitamin e': 0.0,
        'riboflavin': 0.0,
        'niacin': 0,
        'vitamin b6': 0.0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 3,
        'vitamin d': 0
    },
    'olive oil': {
        'quantity': 1,
        'measure': 'teaspoon',
        'calories': 119,
        'protein': 0,
        'carbs': 0,
        'fiber': 0,
        'fat': 14,
        'calcium': 0,
        'iron': 0.09,
        'magnesium': 0,
        'sodium': 0,
        'zinc': 0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 1.94,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'cholesterol': 0,
        'sugar': 2,
        'vitamin d': 0,
        'potassium': 0
    },
    'strawberries': {
        'quantity': 1,
        'measure': 'serving',
        'weight': 2,
        'unit': 'g',
        'calories': 23,
        'protein': 0,
        'carbs': 6,
        'fiber': 1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 12,
        'iron': 0.3,
        'magnesium': 9,
        'sodium': 1,
        'zinc': 0.10,
        'vitamin a': 1,
        'thiamine': 0.02,
        'vitamin e': 0.21,
        'riboflavin': 0.02,
        'niacin': 0.28,
        'vitamin b6': 0.03,
        'folate': 17,
        'vitamin c': 42,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 0,
        'potassium': 110
    },
    'banana': {
        'quantity': 1,
        'measure': 'item',
        'weight': 118,
        'unit': 'g',
        'calories': 105,
        'protein': 1,
        'carbs': 27,
        'fiber': 3.1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 6,
        'iron': 0.31,
        'magnesium': 32,
        'sodium': 1,
        'zinc': 0.18,
        'vitamin a': 4,
        'thiamine': 0.04,
        'vitamin e': 0.12,
        'riboflavin': 0.09,
        'niacin': 0.78,
        'vitamin b6': 0.43,
        'folate': 24,
        'vitamin c': 10,
        'vitamin b12': 0,
        'selenium': 1,
        'sugar': 14,
        'vitamin d': 0,
        'potassium': 422
    },
    'broccoli': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 27,
        'protein': 2,
        'carbs': 6,
        'fiber': 3,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 31,
        'iron': 0.52,
        'magnesium': 16,
        'potassium': 229,
        'sodium': 32,
        'zinc': 0.35,
        'vitamin a': 76,
        'thiamine': 0.05,
        'vitamin e': 1.13,
        'riboflavin': 0.10,
        'niacin': 0.43,
        'vitamin b6': 0.16,
        'folate': 84,
        'vitamin c': 51,
        'vitamin b12': 0,
        'selenium': 1,
        'sugar': 2,
        'vitamin d': 5
    },
    'carrots': {
        'quantity': 8,
        'measure': 'items',
        'weight': 80,
        'unit': 'g',
        'calories': 28,
        'protein': 1,
        'carbs': 7,
        'fiber': 1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 26,
        'iron': 0.71,
        'magnesium': 8,
        'potassium': 190,
        'sodium': 62,
        'zinc': 0.14,
        'vitamin a': 552,
        'thiamine': 0.02,
        'vitamin e': 0.0,
        'riboflavin': 0.03,
        'niacin': 0.44,
        'vitamin b6': 0.08,
        'folate': 26,
        'vitamin c': 7,
        'vitamin b12': 0,
        'selenium': 1,
        'sugar': 4,
        'vitamin d': 0
    },
    'cauliflower': {
        'quantity': 0.5,
        'measure': 'cup',
        'calories': 14,
        'protein': 1,
        'carbs': 3,
        'fiber': 2,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 10,
        'iron': 0.20,
        'magnesium': 6,
        'potassium': 88,
        'sodium': 9,
        'zinc': 0.11,
        'vitamin a': 1,
        'thiamine': 0.03,
        'vitamin e': 0.04,
        'riboflavin': 0.03,
        'niacin': 0.25,
        'vitamin b6': 0.11,
        'folate': 27,
        'vitamin c': 27,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'lentils': {
        'quantity': 1,
        'measure': 'serving',
        'calories': 160,
        'weight': 45,
        'unit': 'g',
        'protein': 11,
        'carbs': 29,
        'fiber': 5,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 16,
        'iron': 3,
        'magnesium': 18,
        'potassium': 305,
        'sodium': 0,
        'zinc': 0.63,
        'vitamin a': 0,
        'thiamine': 0.085,
        'vitamin e': 0.055,
        'riboflavin': 0.035,
        'niacin': 0.525,
        'vitamin b6': 0.09,
        'folate': 89.5,
        'vitamin c': 1.5,
        'vitamin b12': 0,
        'selenium': 1.5,
        'sugar': 1,
        'vitamin d': 0
    },
    'spinach': {
        'quantity': 1,
        'measure': 'cup',
        'calories': 7,
        'protein': 1,
        'carbs': 1,
        'fiber': 1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 30,
        'iron': 0.81,
        'magnesium': 24,
        'potassium': 167,
        'sodium': 24,
        'zinc': 0.16,
        'vitamin a': 141,
        'thiamine': 0.02,
        'vitamin e': 0.61,
        'riboflavin': 0.06,
        'niacin': 0.22,
        'vitamin b6': 0.06,
        'folate': 58,
        'vitamin c': 8,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'tomatoes': {
        'quantity': 1,
        'measure': 'item',
        'calories': 22,
        'protein': 1,
        'carbs': 5,
        'fiber': 1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 12,
        'iron': 0.33,
        'magnesium': 14,
        'potassium': 292,
        'sodium': 6,
        'zinc': 0.20,
        'vitamin a': 76,
        'thiamine': 0.04,
        'vitamin e': 0.66,
        'riboflavin': 0.02,
        'niacin': 0.73,
        'vitamin b6': 0.09,
        'folate': 18,
        'vitamin c': 16,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 5
    },
    'whole milk': {
        'quantity': 1,
        'measure': 'cup',
        'calories': 160,
        'protein': 8,
        'carbs': 12,
        'fiber': 0,
        'fat': 9,
        'cholesterol': 35,
        'calcium': 300,
        'iron': 0,
        'magnesium': 24,
        'potassium': 370,
        'sodium': 125,
        'zinc': 0,
        'vitamin a': 75,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 11,
        'vitamin d': 3
    },
    'egg white': {
        'quantity': 1,
        'measure': 'item',
        'calories': 17,
        'protein': 6,
        'carbs': 1,
        'fiber': 0,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 2,
        'iron': 0.03,
        'magnesium': 4,
        'potassium': 54,
        'sodium': 55,
        'zinc': 0.01,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0.24,
        'niacin': 0.04,
        'vitamin b6': 0.07,
        'folate': 1,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 7,
        'sugar': .6,
        'vitamin d': 0
    },
    'oatmeal': {
        'quantity': 1,
        'measure': 'bowl',
        'calories': 150,
        'protein': 5,
        'carbs': 27,
        'fiber': 4,
        'fat': .5,
        'cholesterol': 0,
        'calcium': 20,
        'iron': 1.5,
        'magnesium': 0,
        'sodium': 0,
        'zinc': 5.9,
        'vitamin a': 0,
        'thiamine': .2,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0.0,
        'vitamin b6': 0.0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 1,
        'vitamin d': 0,
        'potassium': 150
    },
    'greek yogurt (Yoplait)': {
        'quantity': 1,
        'measure': 'cup',
        'weight': 150,
        'unit': 'g',
        'calories': 100,
        'protein': 14,
        'carbs': 10,
        'fiber': 0,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 0,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 55,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 3.3,
        'vitamin d': 0
    },
    'swiss cheese': {
        'quantity': 1,
        'measure': 'slice',
        'weight': 0,
        'unit': 'g',
        'calories': 60,
        'protein': 6,
        'carbs': 0,
        'fiber': 0,
        'fat': 7,
        'cholesterol': 20,
        'calcium': 205,
        'iron': 0,
        'magnesium': 0,
        'potassium': 15,
        'sodium': 45,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'basmati': {
        'quantity': .25,
        'measure': 'cup',
        'weight': 45,
        'unit': 'g',
        'calories': 160,
        'protein': 4,
        'carbs': 35,
        'fiber': 0,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 0,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 0,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'hummus': {
        'quantity': 2,
        'measure': 'tablespoons',
        'weight': 28,
        'unit': 'g',
        'calories': 70,
        'protein': 4,
        'carbs': 6,
        'fiber': 1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 0,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 0,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 0
    },
    'cashews (Kirkland)': {
        'quantity': 1,
        'measure': 'oz',
        'weight': 28,
        'unit': 'g',
        'calories': 160,
        'protein': 5,
        'carbs': 8,
        'fiber': 0,
        'fat': 13,
        'cholesterol': 0,
        'calcium': 0,
        'iron': 1.6,
        'magnesium': 0,
        'sodium': 85,
        'zinc': 1.92,
        'vitamin a': 0,
        'thiamine': 0.07,
        'vitamin e': 0.32,
        'riboflavin': 0.07,
        'niacin': 0.48,
        'vitamin b6': 0.09,
        'folate': 24,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 4,
        'sugar': 1,
        'vitamin d': 0,
        'potassium': 170
    },
    'potato chips (Kettle Brand, Sea Salt)': {
        'quantity': 13,
        'measure': 'items',
        'weight': 28,
        'unit': 'g',
        'calories': 150,
        'protein': 2,
        'carbs': 15,
        'fiber': 2,
        'fat': 9,
        'cholesterol': 0,
        'calcium': 0,
        'iron': 0.4,
        'magnesium': 0,
        'potassium': 330,
        'sodium': 110,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 0
    },
    'mayonnaise (Urban Meadow)': {
        'quantity': 1,
        'measure': 'tbsp',
        'weight': 14,
        'unit': 'g',
        'calories': 100,
        'protein': 0,
        'carbs': 0,
        'fiber': 0,
        'fat': 11,
        'cholesterol': 10,
        'calcium': 0,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 0,
        'zinc': 0.0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 0
    },
    'tuna': {
        'quantity': 1,
        'measure': 'items',
        'weight': 0,
        'unit': 'g',
        'calories': 56,
        'protein': 10.5,
        'carbs': 2.5,
        'fiber': .5,
        'fat': .3,
        'cholesterol': 22.5,
        'calcium': 2.75,
        'iron': 0.0325,
        'magnesium': 1.5,
        'potassium': 22.5,
        'sodium': 135.5,
        'zinc': 0.0275,
        'vitamin a': 0,
        'thiamine': 0.005,
        'vitamin e': 0.0025,
        'riboflavin': 0.0025,
        'niacin': 0.0225,
        'vitamin b6': 0.0175,
        'folate': 2.75,
        'vitamin c': 1,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'yukon gold potatoe': {
        'quantity': .5,
        'measure': 'cup',
        'weight': 78,
        'unit': 'g',
        'calories': 58,
        'protein': 1.6,
        'carbs': 14,
        'fiber': 1.1,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 11,
        'iron': .6,
        'magnesium': 16,
        'sodium': 4,
        'zinc': .21,
        'vitamin a': 0,
        'thiamine': 0.08,
        'vitamin e': 0.01,
        'riboflavin': .01,
        'niacin': 1.02,
        'vitamin b6': 0.21,
        'folate': 7,
        'vitamin c': 6,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0,
        'potassium': 327
    },
    'spring mix': {
        'quantity': 1,
        'measure': 'serving',
        'weight': 85,
        'unit': 'g',
        'calories': 20,
        'protein': 2,
        'carbs': 3,
        'fiber': 2,
        'fat': 0,
        'cholesterol': 0,
        'calcium': 0,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 4,
        'zinc': .21,
        'vitamin a': 0,
        'thiamine': 0.00,
        'vitamin e': 0.01,
        'riboflavin': .01,
        'niacin': 1.02,
        'vitamin b6': 0.21,
        'folate': 60.4,
        'vitamin c': 6,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'ground turkey': {
        'quantity': 1,
        'measure': 'serving',
        'weight': 85,
        'unit': 'g',
        'calories': 200,
        'protein': 23,
        'carbs': 0,
        'fiber': 0,
        'fat': 0,
        'cholesterol': 87,
        'calcium': 21,
        'iron': 1.64,
        'magnesium': 20,
        'potassium': 230,
        'sodium': 91,
        'zinc': 2.43,
        'vitamin a': 0,
        'thiamine': 0.05,
        'vitamin e': 0.29,
        'riboflavin': 0.14,
        'niacin': 4.10,
        'vitamin b6': .33,
        'folate': 6,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'feta': {
        'quantity': .25,
        'measure': 'cup',
        'weight': 28,
        'unit': 'g',
        'calories': 70,
        'protein': 5,
        'carbs': 1,
        'fiber': 0,
        'fat': 6,
        'cholesterol': 20,
        'calcium': 70,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 330,
        'zinc': 0,
        'vitamin a': 0,
        'thiamine': 0,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'sunflower seeds': {
        'quantity': 1,
        'measure': 'oz',
        'weight': 28,
        'unit': 'g',
        'calories': 160,
        'protein': 6,
        'carbs': 7,
        'fiber': 3,
        'fat': 14,
        'cholesterol': 0,
        'calcium': 19,
        'iron': 2.28,
        'magnesium': 43,
        'potassium': 164,
        'sodium': 115,
        'zinc': 1.78,
        'vitamin a': 0,
        'thiamine': 0.11,
        'vitamin e': 0,
        'riboflavin': 0.10,
        'niacin': 1.41,
        'vitamin b6': 0.27,
        'folate': 80,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 21,
        'sugar': 2,
        'vitamin d': 0
    },
    'whey protein (Designer)': {
        'quantity': 1,
        'measure': 'scoop',
        'weight': 31,
        'unit': 'g',
        'calories': 110,
        'protein': 20,
        'carbs': 6,
        'fiber': 23,
        'fat': 1.5,
        'cholesterol': 0,
        'calcium': 0,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 4,
        'zinc': .21,
        'vitamin a': 0,
        'thiamine': 0.00,
        'vitamin e': 0.01,
        'riboflavin': .01,
        'niacin': 1.02,
        'vitamin b6': 0.21,
        'folate': 60.4,
        'vitamin c': 6,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    },
    'Pinto Beans': {
        'quantity': 1,
        'measure': 'serving',
        'weight': 41,
        'unit': 'g',
        'calories': 140,
        'protein': 9,
        'carbs': 28,
        'fiber': 6,
        'fat': .5,
        'cholesterol': 0,
        'calcium': 46,
        'iron': 2,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 0,
        'zinc': 0,
        'vitamin a': 0,
        'thiamine': 0.00,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 1,
        'vitamin d': 0
    },
    'Peanut Butter (JIFFY)': {
        'quantity': 2,
        'measure': 'tablespoon',
        'weight': 33,
        'unit': 'g',
        'calories': 190,
        'protein': 7,
        'carbs': 8,
        'fiber': 2,
        'fat': 16,
        'cholesterol': 0,
        'calcium': 17,
        'iron': 1,
        'magnesium': 49,
        'potassium': 185,
        'sodium': 0,
        'zinc': 0,
        'vitamin a': 0,
        'thiamine': 0.00,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 3,
        'vitamin d': 0
    },
    'Quinoa (Kirkland)': {
        'quantity': .25,
        'measure': 'cup',
        'weight': 44,
        'unit': 'g',
        'calories': 160,
        'protein': 6,
        'carbs': 28,
        'fiber': 3,
        'fat': 2.5,
        'cholesterol': 0,
        'calcium': 0,
        'iron': 2,
        'magnesium': 29.5,
        'potassium': 250,
        'sodium': 0,
        'zinc': .46,
        'vitamin a': 0,
        'thiamine': 0.00,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 2,
        'vitamin d': 0
    },
    'Shaved Parmesan (Publix)': {
        'quantity': 1,
        'measure': 'ounce',
        'weight': 28,
        'unit': 'g',
        'calories': 110,
        'protein': 9,
        'carbs': 1,
        'fiber': 1,
        'fat': 8,
        'cholesterol': 25,
        'calcium': 0,
        'iron': 0,
        'magnesium': 0,
        'potassium': 0,
        'sodium': 360,
        'zinc': 0,
        'vitamin a': 0,
        'thiamine': 0.00,
        'vitamin e': 0,
        'riboflavin': 0,
        'niacin': 0,
        'vitamin b6': 0,
        'folate': 0,
        'vitamin c': 0,
        'vitamin b12': 0,
        'selenium': 0,
        'sugar': 0,
        'vitamin d': 0
    }
}
